openapi: 3.0.4
info:
  title: Workout App
  description: 'Api для взаимодействия с бэкендом Воркаут Приложения'
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://localhost:8080/v1
tags:
  - name: workout
    description: Тренировка
paths:
  /program/create:
    post:
      tags:
        - program
      summary: Создание программы
      operationId: createProgream
      requestBody:
        description: Запрос на создание программы
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProgramRequest'
      responses:
        200:
          description: all responses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateProgramResponse'

  /program/search:
    post:
      tags:
        - program
      summary: Поиск программ
      operationId: searchProgram
      requestBody:
        description: Объект запроса поиска программм
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchProgramRequest'
        required: true
      responses:
        200:
          description: all responses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchProgramResponse'

  /program/read:
    post:
      tags:
        - program
      summary: Поиск программ
      operationId: readProgram
      requestBody:
        description: Объект запроса для просмотра программы
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReadProgramRequest'
        required: true
      responses:
        200:
          description: all responses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReadProgramResponse'

  /program/update:
    post:
      tags:
        - program
      summary: Обновление информации в программе
      operationId: updateProgram
      requestBody:
        description: Объект запроса обновления информации программы
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProgramRequest'
        required: true
      responses:
        200:
          description: all responses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateProgramResponse'

  /program/delete:
    post:
      tags:
        - program
      summary: Обновление информации в программе
      operationId: deleteProgram
      requestBody:
        description: Объект запроса обновления информации программы
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProgramRequest'
        required: true
      responses:
        200:
          description: all responses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteProgramResponse'

  /workout/create:
    post:
      tags:
        - workout
      summary: Создание новой тренировки в программе
      operationId: createWorkout
      requestBody:
        description: Объект запроса создания новой тренировки
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateWorkoutRequest'
        required: true
      responses:
        200:
          description: all responses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateWorkoutResponse'

  /workout/update:
    post:
      tags:
        - workout
      summary: Обновление существующей тренировки в программе
      operationId: updateWorkout
      requestBody:
        description: Объект запроса обновления информации в существующей тренировке
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateWorkoutRequest'
        required: true
      responses:
        200:
          description: all responses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateWorkoutResponse'

  /workout/delete:
    post:
      tags:
        - workout
      summary: Удалить тренировку
      operationId: deleteWorkout
      requestBody:
        description: Объект запроса на удаление существующей тренировки
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteWorkoutRequest'
        required: true
      responses:
        200:
          description: all responses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteWorkoutResponse'

  /feedback/create:
    post:
      tags:
        - feedback
      summary: Создать отзыв
      operationId: createFeedback
      requestBody:
        description: Объект запроса на создание фидбэка для програмы или тренировки
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateFeedbackRequest'
        required: true
      responses:
        200:
          description: all responses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateFeedbackResponse'

  /feedback/update:
    post:
      tags:
        - feedback
      summary: Редактировать отзыв
      operationId: updateFeedback
      requestBody:
        description: Объект запроса на создание фидбэка для програмы или тренировки
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateFeedbackRequest'
        required: true
      responses:
        200:
          description: all responses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateFeedbackResponse'

  /feedback/read:
    post:
      tags:
        - feedback
      summary: Просмотреть отзывы
      operationId: readFeedback
      requestBody:
        description: Объект запроса на получение отзывов о программе или тренировке
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateFeedbackRequest'
        required: true
      responses:
        200:
          description: all responses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateFeedbackResponse'

  /feedback/delete:
    post:
      tags:
        - feedback
      summary: Удалить отзыв
      operationId: deleteFeedback
      requestBody:
        description: Объект запроса на удаление отзыва
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteFeedbackRequest'
        required: true
      responses:
        200:
          description: all responses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteFeedbackResponse'

components:
  schemas:

    ProgramRequestDebugMode:
      type: string
      enum:
        - prod
        - test
        - stub

    IRequest:
      type: object
      description: Базовый интерфейс для всех запросов
      properties:
        requestType:
          type: string
          description: Поле-дискриминатор для вычисления типа запроса
          example: createProgram
        requestId:
          type: string
          description: Идентификатор запроса для отладки
      discriminator:
        propertyName: requestType
        mapping:
          createProgram: '#/components/schemas/CreateProgramRequest'
          readProgram: '#/components/schemas/ReadProgramRequest'
          updateProgram: '#/components/schemas/UpdateProgramRequest'
          deleteProgram: '#/components/schemas/DeleteProgramRequest'
          searchProgram: '#/components/schemas/SearchProgramRequest'
          createWorkout: '#/components/schemas/CreateWorkoutRequest'
          readWorkout: '#/components/schemas/ReadWorkoutRequest'
          updateWorkout: '#/components/schemas/UpdateWorkoutRequest'
          deleteWorkout: '#/components/schemas/DeleteWorkoutRequest'
          searchWorkout: '#/components/schemas/SearchWorkoutRequest'
          createFeedback: '#/components/schemas/CreateFeedbackRequest'
          readFeedback: '#/components/schemas/ReadFeedbackRequest'
          updateFeedback: '#/components/schemas/UpdateWorkoutRequest'
          deleteFeedback: '#/components/schemas/DeleteFeedbackRequest'
          searchFeedback: '#/components/schemas/SearchFeedbackRequest'

    IResponse:
      type: object
      description: Базовый интерфейс для всех ответов
      properties:
        requestType:
          type: string
          description: Поле-дискриминатор для вычисления типа запроса
          example: createProgram
        requestId:
          type: string
          description: Идентификатор  для отладки
        result:
          $ref: '#/components/schemas/ResponseResult'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
      discriminator:
        propertyName: responseType
        mapping:
          createProgram: '#/components/schemas/CreateProgramResponse'
          readProgram: '#/components/schemas/ReadProgramResponse'
          updateProgram: '#/components/schemas/UpdateProgramResponse'
          deleteProgram: '#/components/schemas/DeleteProgramResponse'
          searchProgram: '#/components/schemas/SearchProgramResponse'
          createWorkout: '#/components/schemas/CreateWorkoutResponse'
          readWorkout: '#/components/schemas/ReadWorkoutRequest'
          updateWorkout: '#/components/schemas/UpdateWorkoutResponse'
          deleteWorkout: '#/components/schemas/DeleteWorkoutResponse'
          searchWorkout: '#/components/schemas/SearchWorkoutResponse'
          createFeedback: '#/components/schemas/CreateFeedbackResponse'
          readFeedback: '#/components/schemas/ReadFeedbackResponse'
          updateFeedback: '#/components/schemas/UpdateWorkoutResponse'
          deleteFeedback: '#/components/schemas/DeleteFeedbackResponse'
          searchFeedback: '#/components/schemas/SearchFeedbackResponse'

    Error:
      type: object
      properties:
        code:
          type: string
        group:
          type: string
        field:
          type: string
        message:
          type: string

    ResponseResult:
      type: string
      enum:
        - success
        - error

    Program:
      type: object
      properties:
        title:
          type: string
          description: Название программы
        description:
          type: string
          description: Описание программы
        difficulty:
          type: string
          description: Уровень сложности
        equipment:
          type: array
          items:
            $ref: '#/components/schemas/Equipment'
          description: Список оборудования
        workouts:
          type: array
          items:
            $ref: '#/components/schemas/Workout'
          description: Состав тренировок
        rating:
          type: integer
          description: Общая оценка программы от всех пользователей, кто пометил ее выполненной
        feedback:
          type: array
          items:
            $ref: '#/components/schemas/ProgramFeedback'
          description: Отзывы пользователей

    Workout:
      type: object
      properties:
        title:
          type: string
          description: Ссылка на видеоматериал тренировки
        description:
          type: string
          description: Ссылка на видеоматериал тренировки
        equipment:
          type: array
          description: Оборудование для тренировки
          items:
            $ref: '#/components/schemas/Equipment'
        content:
          type: object
          description: Содержание тренировки
          allOf:
            - $ref: '#/components/schemas/WorkoutContent'
        feedback:
          type: object
          description: Отзывы о тренировке
          allOf:
            - $ref: '#/components/schemas/WorkoutFeedback'

    WorkoutContent:
      type: object
      properties:
        video:
          type: string
          description: Ссылка на видеоматериал тренировки
        steps:
          type: array
          description: Пошаговое описание тренировки
          items:
            type: string

    WorkoutFeedback:
      type: object
      properties:
        isFinished:
          type: boolean
          description: выполнена/не выполнена - проставляется пользователем самостоятельно
        review:
          type: string
          description: отзыв пользователя о тренировке

    ProgramFeedback:
      type: object
      properties:
        isStarted:
          type: boolean
          description: начата/не начата (проставляется автоматически при включении первой тренировки из программы)
        isFinished:
          type: boolean
          description: выполнена/не выполнена (проставляется автоматически по завершении всех тренировок в программе)
        progress:
          type: integer
          description: процент выполнения программы
        rating:
          type: integer
          description: оценка пользователя
        review:
          type: object
          oneOf:
            - $ref: '#/components/schemas/Review'
          description: отзыв пользователя

    Review:
      type: object
      required:
        - stats
      properties:
        comment:
          type: string
          description: текстовый комментарий
        photos:
          type: object
          description: фотографии до/после
          properties:
            content:
              type: array
              items:
                type: string
              description: лист ссылок на фото
            isPrivate:
              type: boolean
              description: фото скрыты из общего доступа
        stats:
          type: object
          description: Оценка пользователя по параметрам
          properties:
            difficulty:
              type: integer
              description: сложность от 1 до 5
            intensivity:
              type: integer
              description: интенесивность от 1 до 5
            interestingness:
              type: integer
              description: интересность от 1 до 5


    Difficulty:
      type: string
      enum:
        - beginner
        - medium
        - advanced

    Equipment:
      type: string
      enum:
        - ownWeight
        - dumbbells
        - jumpingRope
        - horizontalBar
        - bars

    CreateProgramRequest:
      type: object

    CreateProgramResponse:
      type: object

    UpdateProgramRequest:
      type: object

    UpdateProgramResponse:
      type: object

    DeleteProgramRequest:
      type: object

    DeleteProgramResponse:
      type: object

    SearchProgramRequest:
      type: object

    SearchProgramResponse:
      type: object

    ReadProgramRequest:
      type: object

    ReadProgramResponse:
      type: object

    CreateWorkoutRequest:
      type: object

    CreateWorkoutResponse:
      type: object

    UpdateWorkoutRequest:
      type: object

    UpdateWorkoutResponse:
      type: object

    DeleteWorkoutRequest:
      type: object

    DeleteWorkoutResponse:
      type: object

    GetWorkoutRequest:
      type: object

    GetWorkoutResponse:
      type: object

    CreateFeedbackRequest:
      type: object

    CreateFeedbackResponse:
      type: object

    UpdateFeedbackRequest:
      type: object

    UpdateFeedbackResponse:
      type: object

    DeleteFeedbackRequest:
      type: object

    DeleteFeedbackResponse:
      type: object
